##
# @file main_window.py
# @brief Main application window for the Aurumveil platform.
#
# Defines the primary user interface container responsible
# for hosting the content and control panels, managing
# inter-panel communication, and handling responsive
# user interface scaling.
#

from pathlib import Path

from PySide6.QtGui import (
    QIcon,
    QResizeEvent,
)

from PySide6.QtWidgets import (
    QHBoxLayout,
    QVBoxLayout,
    QWidget,
)

from interface.content_panel import ContentPanel
from interface.control_panel import ControlPanel
from interface.widget_effects import apply_shadow


##
# @brief Main application window.
#
# Serves as the central container of the graphical
# user interface. The window coordinates communication
# between the content and control panels, manages
# application-wide layout configuration, and applies
# responsive visual adjustments during resizing.
#
class MainWindow(QWidget):

    ##
    # @brief Creates and initializes the main application window.
    #
    # Configures the window title, icon, dimensions,
    # and initializes the graphical user interface.
    #
    # @return None
    #
    def __init__(self) -> None:
        super().__init__()

        # ===== WINDOW TITLE =====
        self.setWindowTitle(
            "Aurumveil • Optimization & Analysis System"
        )

        # ===== WINDOW ICON =====
        icon_path = (
            Path(__file__).resolve().parent.parent
            / "assets"
            / "icons"
            / "aurumveil.ico"
        )

        self.setWindowIcon(
            QIcon(str(icon_path))
        )

        # ===== WINDOW SIZE =====
        self.setMinimumSize(1200, 700)
        self.resize(1200, 750)

        # ===== USER INTERFACE =====
        self._initialize_ui()

    ##
    # @brief Builds the user interface layout.
    #
    # Creates the root container, initializes content
    # and control panels, establishes signal connections,
    # and configures the main application layout.
    #
    # @return None
    #
    def _initialize_ui(self) -> None:

        # ===== ROOT LAYOUT =====
        root_layout: QVBoxLayout = QVBoxLayout(self)

        root_layout.setContentsMargins(
            20,
            20,
            20,
            20,
        )

        # ===== APP CONTAINER =====
        self.background_widget: QWidget = QWidget()

        self.background_widget.setObjectName(
            "AppContainer"
        )

        apply_shadow(self.background_widget)

        # ===== CONTENT LAYOUT =====
        content_layout: QHBoxLayout = QHBoxLayout(
            self.background_widget
        )

        content_layout.setContentsMargins(
            16,
            16,
            16,
            16,
        )

        content_layout.setSpacing(4)

        # ===== PANELS =====
        self.content_panel: ContentPanel = ContentPanel()
        self.control_panel: ControlPanel = ControlPanel()

        self.content_panel.control_panel = (
            self.control_panel
        )

        self.control_panel.setFixedWidth(320)

        # ===== SIGNALS =====
        self.control_panel.log_signal.connect(
            self._handle_log
        )

        self.control_panel.refresh_graph_signal.connect(
            self.content_panel.redraw_graph
        )

        # ===== PANEL LAYOUT =====
        content_layout.addWidget(
            self.content_panel,
            7,
        )

        content_layout.addWidget(
            self.control_panel,
            3,
        )

        # ===== ROOT LAYOUT =====
        root_layout.addWidget(
            self.background_widget
        )

    ##
    # @brief Processes log messages emitted by the control panel.
    #
    # Forwards log entries to the content panel for
    # visualization within the application log view.
    #
    # @param log_entry
    # Log message generated by the control panel.
    #
    # @return None
    #
    def _handle_log(self, log_entry: str) -> None:

        self.content_panel.append_system_log(log_entry)

    ##
    # @brief Handles window resize events.
    #
    # Dynamically adjusts button dimensions, font sizes,
    # spacing, and border radii to maintain a consistent
    # visual appearance across different window sizes.
    #
    # @param event
    # Qt resize event containing the updated window size.
    #
    # @return None
    #
    def resizeEvent(self, event: QResizeEvent) -> None:
        super().resizeEvent(event)

        # ===== BASE SIZE =====
        base_width: int = 1200
        base_height: int = 750

        # ===== SCALE =====
        scale: float = min(
            self.width() / base_width,
            self.height() / base_height,
        )

        scale: float = max(
            1.05,
            min(scale, 1.7),
        )

        # ===== METRICS =====
        vertical_padding: int = int(6 * scale)
        horizontal_padding: int = int(14 * scale)

        border_radius: int = int(14 * scale)
        font_size: int = int(12 * scale)

        segment_radius: int = int(border_radius * 0.6)

        # ===== DYNAMIC STYLESHEET =====
        responsive_stylesheet: str = f"""
        /* ===== SECONDARY BUTTON ===== */
        QPushButton#SecondaryButton {{
            border-radius: {border_radius}px;

            padding: {vertical_padding}px {horizontal_padding}px;

            font-size: {font_size}px;
        }}


        /* ===== SEGMENT BUTTON ===== */
        QPushButton#SegmentButton {{
            padding: {vertical_padding}px {int(horizontal_padding * 0.8)}px;

            font-size: {font_size}px;
        }}

        QPushButton#SegmentButton:first {{
            border-top-left-radius: {segment_radius}px;
            border-bottom-left-radius: {segment_radius}px;
        }}

        QPushButton#SegmentButton:last {{
            border-top-right-radius: {segment_radius}px;
            border-bottom-right-radius: {segment_radius}px;
        }}


        /* ===== PRIMARY BUTTON ===== */
        QPushButton#PrimaryButton {{
            border-radius: {border_radius}px;

            padding: {vertical_padding}px {horizontal_padding}px;

            font-size: {font_size}px;
        }}
        """

        self.setStyleSheet(responsive_stylesheet)